### ISSUE TITLE
Rename repository to faunadb-vercel-sample-app

### ISSUE THREAD

**Issue by pranavnt** [fauna/faunadb-zeit-sample-app#10]
This really isn't a big deal, but I think it might be helpful if the repository was renamed to "faunadb-vercel-sample-app", as Zeit has recently changed their name to Vercel. This might be extra useful in the future, especially if developers forget that Vercel's old name was Zeit.

Thanks for all the awesome work you do at Fauna and it is amazing!

**Comment by rts-rob** [comment]
Thank you for submitting this issue. We are deprecating and archiving this repository in favor of https://github.com/vercel/next.js/tree/canary/examples/with-fauna

Closing this issue pre-archival.
