### ISSUE TITLE
should we disable keepAlive in zeit api lambdas?

### ISSUE THREAD

**Issue by vasco3** [fauna/faunadb-zeit-sample-app#2]
https://github.com/fauna/faunadb-zeit-sample-app/blob/3afc598f766a92b4dd2cce6769333896d5589ecc/pages/api/collections.js#L8

**Comment by rts-rob** [comment]
Thank you for submitting this issue. We are deprecating and archiving this repository in favor of https://github.com/vercel/next.js/tree/canary/examples/with-fauna

Closing this issue pre-archival.
