### ISSUE TITLE
Question: Does this support local development?

### ISSUE THREAD

**Issue by donedgardo** [fauna/faunadb-zeit-sample-app#4]
Looking at the following code I noticed developing locally is not possible, is there a way around this?
```jsx
App.getInitialProps = async ({ req }) => {
  try {
    const { 'x-now-deployment-url': nowURL } = req.headers;

    if (!nowURL) {
      throw new NotDeployedError();
    }
```

**Comment by tavoli** [comment]
You need run the command **vercel env pull** and restart your app.
Dont forget that the variable need be inserted on dashboard configurations of development workspace.

**Comment by rts-rob** [comment]
Thank you for submitting this issue. We are deprecating and archiving this repository in favor of https://github.com/vercel/next.js/tree/canary/examples/with-fauna

Closing this issue pre-archival.
